###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file cy_GB.xml
# The source file version number was 1.40, generated on
# 2007/07/19 22:31:38.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::cy_GB;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::cy';

{
    my $first_day_of_week = 7;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::cy_GB

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'cy_GB' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Welsh United Kingdom.

=head1 DATA

This locale inherits from the L<DateTime::Locale::cy> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  Dydd Llun
  Dydd Mawrth
  Dydd Mercher
  Dydd Iau
  Dydd Gwener
  Dydd Sadwrn
  Dydd Sul

=head3 Abbreviated (format)

  Llun
  Maw
  Mer
  Iau
  Gwen
  Sad
  Sul

=head3 Narrow (format)

  L
  M
  M
  I
  G
  S
  S

=head3 Wide (stand-alone)

  Dydd Llun
  Dydd Mawrth
  Dydd Mercher
  Dydd Iau
  Dydd Gwener
  Dydd Sadwrn
  Dydd Sul

=head3 Abbreviated (stand-alone)

  Llun
  Maw
  Mer
  Iau
  Gwen
  Sad
  Sul

=head3 Narrow (stand-alone)

  L
  M
  M
  I
  G
  S
  S

=head2 Months

=head3 Wide (format)

  Ionawr
  Chwefror
  Mawrth
  Ebrill
  Mai
  Mehefin
  Gorffenaf
  Awst
  Medi
  Hydref
  Tachwedd
  Rhagfyr

=head3 Abbreviated (format)

  Ion
  Chwef
  Mawrth
  Ebrill
  Mai
  Meh
  Gorff
  Awst
  Medi
  Hyd
  Tach
  Rhag

=head3 Narrow (format)

  I
  C
  M
  E
  M
  M
  G
  A
  M
  H
  T
  R

=head3 Wide (stand-alone)

  Ionawr
  Chwefror
  Mawrth
  Ebrill
  Mai
  Mehefin
  Gorffenaf
  Awst
  Medi
  Hydref
  Tachwedd
  Rhagfyr

=head3 Abbreviated (stand-alone)

  Ion
  Chwef
  Mawrth
  Ebrill
  Mai
  Meh
  Gorff
  Awst
  Medi
  Hyd
  Tach
  Rhag

=head3 Narrow (stand-alone)

  I
  C
  M
  E
  M
  M
  G
  A
  M
  H
  T
  R

=head2 Quarters

=head3 Wide (format)

  Q1
  Q2
  Q3
  Q4

=head3 Abbreviated (format)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  Q1
  Q2
  Q3
  Q4

=head3 Abbreviated (stand-alone)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  BCE
  CE

=head3 Abbreviated

  BCE
  CE

=head3 Narrow

  BCE
  CE

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = Dydd Mawrth, 05 Chwefror 2008
   1995-12-22T09:05:02 = Dydd Gwener, 22 Rhagfyr 1995
  -0010-12-22T23:05:02 = Dydd Sadwrn, 22 Rhagfyr -010

=head3 Long

   2008-02-05T12:30:30 = 05 Chwefror 2008
   1995-12-22T09:05:02 = 22 Rhagfyr 1995
  -0010-12-22T23:05:02 = 22 Rhagfyr -010

=head3 Medium

   2008-02-05T12:30:30 = 5 Chwef 2008
   1995-12-22T09:05:02 = 22 Rhag 1995
  -0010-12-22T23:05:02 = 22 Rhag -010

=head3 Short

   2008-02-05T12:30:30 = 05/02/2008
   1995-12-22T09:05:02 = 22/12/1995
  -0010-12-22T23:05:02 = 22/12/-010

=head3 Default

   2008-02-05T12:30:30 = 5 Chwef 2008
   1995-12-22T09:05:02 = 22 Rhag 1995
  -0010-12-22T23:05:02 = 22 Rhag -010

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = Dydd Mawrth, 05 Chwefror 2008 12:30:30 UTC
   1995-12-22T09:05:02 = Dydd Gwener, 22 Rhagfyr 1995 09:05:02 UTC
  -0010-12-22T23:05:02 = Dydd Sadwrn, 22 Rhagfyr -010 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 05 Chwefror 2008 12:30:30 UTC
   1995-12-22T09:05:02 = 22 Rhagfyr 1995 09:05:02 UTC
  -0010-12-22T23:05:02 = 22 Rhagfyr -010 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 5 Chwef 2008 12:30:30
   1995-12-22T09:05:02 = 22 Rhag 1995 09:05:02
  -0010-12-22T23:05:02 = 22 Rhag -010 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 05/02/2008 12:30
   1995-12-22T09:05:02 = 22/12/1995 09:05
  -0010-12-22T23:05:02 = 22/12/-010 23:05

=head3 Default

   2008-02-05T12:30:30 = 5 Chwef 2008 12:30:30
   1995-12-22T09:05:02 = 22 Rhag 1995 09:05:02
  -0010-12-22T23:05:02 = 22 Rhag -010 23:05:02

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = Maw 5
   1995-12-22T09:05:02 = Gwen 22
  -0010-12-22T23:05:02 = Sad 22

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-12-22T23:05:02 = 23

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = Maw Chwef 5
   1995-12-22T09:05:02 = Gwen Rhag 22
  -0010-12-22T23:05:02 = Sad Rhag 22

=head3 MMMMd (MMMM d)

   2008-02-05T12:30:30 = Chwefror 5
   1995-12-22T09:05:02 = Rhagfyr 22
  -0010-12-22T23:05:02 = Rhagfyr 22

=head3 MMMMdd (dd MMMM)

   2008-02-05T12:30:30 = 05 Chwefror
   1995-12-22T09:05:02 = 22 Rhagfyr
  -0010-12-22T23:05:02 = 22 Rhagfyr

=head3 MMdd (dd/MM)

   2008-02-05T12:30:30 = 05/02
   1995-12-22T09:05:02 = 22/12
  -0010-12-22T23:05:02 = 22/12

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-12-22T23:05:02 = 12-22

=head3 hhmm (hh:mm a)

   2008-02-05T12:30:30 = 12:30 PM
   1995-12-22T09:05:02 = 09:05 AM
  -0010-12-22T23:05:02 = 11:05 PM

=head3 hhmmss (hh:mm:ss a)

   2008-02-05T12:30:30 = 12:30:30 PM
   1995-12-22T09:05:02 = 09:05:02 AM
  -0010-12-22T23:05:02 = 11:05:02 PM

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-12-22T23:05:02 = 05:02

=head3 yyMM (yy-MM)

   2008-02-05T12:30:30 = 8-02
   1995-12-22T09:05:02 = 95-12
  -0010-12-22T23:05:02 = 10-12

=head3 yyMMM (yy MMM)

   2008-02-05T12:30:30 = 8 Chwef
   1995-12-22T09:05:02 = 95 Rhag
  -0010-12-22T23:05:02 = 10 Rhag

=head3 yyMMdd (yy-MM-dd)

   2008-02-05T12:30:30 = 8-02-05
   1995-12-22T09:05:02 = 95-12-22
  -0010-12-22T23:05:02 = 10-12-22

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-12-22T23:05:02 = 4 10

=head3 yyQQQQ (QQQQ yy)

   2008-02-05T12:30:30 = Q1 8
   1995-12-22T09:05:02 = Q4 95
  -0010-12-22T23:05:02 = Q4 10

=head3 yyyy (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-12-22T23:05:02 = -010

=head3 yyyyMM (MM/yyyy)

   2008-02-05T12:30:30 = 02/2008
   1995-12-22T09:05:02 = 12/1995
  -0010-12-22T23:05:02 = 12/-010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = Chwefror 2008
   1995-12-22T09:05:02 = Rhagfyr 1995
  -0010-12-22T23:05:02 = Rhagfyr -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

Dydd Sul


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
