###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file fur_IT.xml
# The source file version number was 1.13, generated on
# 2007/07/19 22:31:39.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::fur_IT;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::fur';

{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::fur_IT

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'fur_IT' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Friulian Italy.

=head1 DATA

This locale inherits from the L<DateTime::Locale::fur> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  lunis
  martars
  miercus
  joibe
  vinars
  sabide
  domenie

=head3 Abbreviated (format)

  lun
  mar
  mie
  joi
  vin
  sab
  dom

=head3 Narrow (format)

  L
  M
  M
  J
  V
  S
  D

=head3 Wide (stand-alone)

  lunis
  martars
  miercus
  joibe
  vinars
  sabide
  domenie

=head3 Abbreviated (stand-alone)

  lun
  mar
  mie
  joi
  vin
  sab
  dom

=head3 Narrow (stand-alone)

  L
  M
  M
  J
  V
  S
  D

=head2 Months

=head3 Wide (format)

  Zenâr
  Fevrâr
  Març
  Avrîl
  Mai
  Jugn
  Lui
  Avost
  Setembar
  Otubar
  Novembar
  Dicembar

=head3 Abbreviated (format)

  Zen
  Fev
  Mar
  Avr
  Mai
  Jug
  Lui
  Avo
  Set
  Otu
  Nov
  Dic

=head3 Narrow (format)

  Z
  F
  M
  A
  M
  J
  L
  A
  S
  O
  N
  D

=head3 Wide (stand-alone)

  Zenâr
  Fevrâr
  Març
  Avrîl
  Mai
  Jugn
  Lui
  Avost
  Setembar
  Otubar
  Novembar
  Dicembar

=head3 Abbreviated (stand-alone)

  Zen
  Fev
  Mar
  Avr
  Mai
  Jug
  Lui
  Avo
  Set
  Otu
  Nov
  Dic

=head3 Narrow (stand-alone)

  Z
  F
  M
  A
  M
  J
  L
  A
  S
  O
  N
  D

=head2 Quarters

=head3 Wide (format)

  Prin trimestri
  Secont trimestri
  Tierç trimestri
  Cuart trimestri

=head3 Abbreviated (format)

  T1
  T2
  T3
  T4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  Prin trimestri
  Secont trimestri
  Tierç trimestri
  Cuart trimestri

=head3 Abbreviated (stand-alone)

  T1
  T2
  T3
  T4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  pdC
  ddC

=head3 Abbreviated

  pdC
  ddC

=head3 Narrow

  pdC
  ddC

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = 5 Fevrâr 2008 martars
   1995-12-22T09:05:02 = 22 Dicembar 1995 vinars
  -0010-12-22T23:05:02 = 22 Dicembar -010 sabide

=head3 Long

   2008-02-05T12:30:30 = 5 Fevrâr 2008
   1995-12-22T09:05:02 = 22 Dicembar 1995
  -0010-12-22T23:05:02 = 22 Dicembar -010

=head3 Medium

   2008-02-05T12:30:30 = 5 Fev 2008
   1995-12-22T09:05:02 = 22 Dic 1995
  -0010-12-22T23:05:02 = 22 Dic -010

=head3 Short

   2008-02-05T12:30:30 = 5/02/8
   1995-12-22T09:05:02 = 22/12/95
  -0010-12-22T23:05:02 = 22/12/10

=head3 Default

   2008-02-05T12:30:30 = 5 Fev 2008
   1995-12-22T09:05:02 = 22 Dic 1995
  -0010-12-22T23:05:02 = 22 Dic -010

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = 5 Fevrâr 2008 martars 12:30:30 UTC
   1995-12-22T09:05:02 = 22 Dicembar 1995 vinars 09:05:02 UTC
  -0010-12-22T23:05:02 = 22 Dicembar -010 sabide 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 5 Fevrâr 2008 12:30:30 UTC
   1995-12-22T09:05:02 = 22 Dicembar 1995 09:05:02 UTC
  -0010-12-22T23:05:02 = 22 Dicembar -010 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 5 Fev 2008 12:30:30
   1995-12-22T09:05:02 = 22 Dic 1995 09:05:02
  -0010-12-22T23:05:02 = 22 Dic -010 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 5/02/8 12:30
   1995-12-22T09:05:02 = 22/12/95 09:05
  -0010-12-22T23:05:02 = 22/12/10 23:05

=head3 Default

   2008-02-05T12:30:30 = 5 Fev 2008 12:30:30
   1995-12-22T09:05:02 = 22 Dic 1995 09:05:02
  -0010-12-22T23:05:02 = 22 Dic -010 23:05:02

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = mar 5
   1995-12-22T09:05:02 = vin 22
  -0010-12-22T23:05:02 = sab 22

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-12-22T23:05:02 = 23

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = mar Fev 5
   1995-12-22T09:05:02 = vin Dic 22
  -0010-12-22T23:05:02 = sab Dic 22

=head3 MMMMd (d MMMM)

   2008-02-05T12:30:30 = 5 Fevrâr
   1995-12-22T09:05:02 = 22 Dicembar
  -0010-12-22T23:05:02 = 22 Dicembar

=head3 MMd (d/MM)

   2008-02-05T12:30:30 = 5/02
   1995-12-22T09:05:02 = 22/12
  -0010-12-22T23:05:02 = 22/12

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-12-22T23:05:02 = 12-22

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-12-22T23:05:02 = 05:02

=head3 yyMM (MM/yy)

   2008-02-05T12:30:30 = 02/8
   1995-12-22T09:05:02 = 12/95
  -0010-12-22T23:05:02 = 12/10

=head3 yyMMM (yy MMM)

   2008-02-05T12:30:30 = 8 Fev
   1995-12-22T09:05:02 = 95 Dic
  -0010-12-22T23:05:02 = 10 Dic

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-12-22T23:05:02 = 4 10

=head3 yyyy (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-12-22T23:05:02 = -010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = Fevrâr 2008
   1995-12-22T09:05:02 = Dicembar 1995
  -0010-12-22T23:05:02 = Dicembar -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

lunis


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
