###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file hi_IN.xml
# The source file version number was 1.52, generated on
# 2007/07/19 22:31:39.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::hi_IN;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::hi';

{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::hi_IN

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'hi_IN' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Hindi India.

=head1 DATA

This locale inherits from the L<DateTime::Locale::hi> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  सोमवार
  मंगलवार
  बुधवार
  गुरुवार
  शुक्रवार
  शनिवार
  रविवार

=head3 Abbreviated (format)

  सोम
  मंगल
  बुध
  गुरु
  शुक्र
  शनि
  रवि

=head3 Narrow (format)

  2
  3
  4
  5
  6
  7
  1

=head3 Wide (stand-alone)

  सोमवार
  मंगलवार
  बुधवार
  गुरुवार
  शुक्रवार
  शनिवार
  रविवार

=head3 Abbreviated (stand-alone)

  सोम
  मंगल
  बुध
  गुरु
  शुक्र
  शनि
  रवि

=head3 Narrow (stand-alone)

  2
  3
  4
  5
  6
  7
  1

=head2 Months

=head3 Wide (format)

  जनवरी
  फरवरी
  मार्च
  अप्रैल
  मई
  जून
  जुलाई
  अगस्त
  सितम्बर
  अक्तूबर
  नवम्बर
  दिसम्बर

=head3 Abbreviated (format)

  जनवरी
  फरवरी
  मार्च
  अप्रैल
  मई
  जून
  जुलाई
  अगस्त
  सितम्बर
  अक्तूबर
  नवम्बर
  दिसम्बर

=head3 Narrow (format)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head3 Wide (stand-alone)

  जनवरी
  फरवरी
  मार्च
  अप्रैल
  मई
  जून
  जुलाई
  अगस्त
  सितम्बर
  अक्तूबर
  नवम्बर
  दिसम्बर

=head3 Abbreviated (stand-alone)

  जनवरी
  फरवरी
  मार्च
  अप्रैल
  मई
  जून
  जुलाई
  अगस्त
  सितम्बर
  अक्तूबर
  नवम्बर
  दिसम्बर

=head3 Narrow (stand-alone)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head2 Quarters

=head3 Wide (format)

  पॆहला हंत 1
  दूसरा हंत 2
  तीसरा हंत 3
  चौता हंत 4

=head3 Abbreviated (format)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  पॆहला हंत 1
  दूसरा हंत 2
  तीसरा हंत 3
  चौता हंत 4

=head3 Abbreviated (stand-alone)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  BCE
  CE

=head3 Abbreviated

  ईसापूर्व
  सन

=head3 Narrow

  ईसापूर्व
  सन

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = मंगलवार 5 फरवरी 2008
   1995-12-22T09:05:02 = शुक्रवार 22 दिसम्बर 1995
  -0010-12-22T23:05:02 = शनिवार 22 दिसम्बर -010

=head3 Long

   2008-02-05T12:30:30 = 5 फरवरी 2008
   1995-12-22T09:05:02 = 22 दिसम्बर 1995
  -0010-12-22T23:05:02 = 22 दिसम्बर -010

=head3 Medium

   2008-02-05T12:30:30 = 05-02-2008
   1995-12-22T09:05:02 = 22-12-1995
  -0010-12-22T23:05:02 = 22-12--010

=head3 Short

   2008-02-05T12:30:30 = 5-2-8
   1995-12-22T09:05:02 = 22-12-95
  -0010-12-22T23:05:02 = 22-12-10

=head3 Default

   2008-02-05T12:30:30 = 05-02-2008
   1995-12-22T09:05:02 = 22-12-1995
  -0010-12-22T23:05:02 = 22-12--010

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 अपराह्न UTC
   1995-12-22T09:05:02 = 9:05:02 पूर्वाह्न UTC
  -0010-12-22T23:05:02 = 11:05:02 अपराह्न UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 अपराह्न UTC
   1995-12-22T09:05:02 = 9:05:02 पूर्वाह्न UTC
  -0010-12-22T23:05:02 = 11:05:02 अपराह्न UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30 अपराह्न
   1995-12-22T09:05:02 = 9:05:02 पूर्वाह्न
  -0010-12-22T23:05:02 = 11:05:02 अपराह्न

=head3 Short

   2008-02-05T12:30:30 = 12:30 अपराह्न
   1995-12-22T09:05:02 = 9:05 पूर्वाह्न
  -0010-12-22T23:05:02 = 11:05 अपराह्न

=head3 Default

   2008-02-05T12:30:30 = 12:30:30 अपराह्न
   1995-12-22T09:05:02 = 9:05:02 पूर्वाह्न
  -0010-12-22T23:05:02 = 11:05:02 अपराह्न

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = मंगलवार 5 फरवरी 2008 12:30:30 अपराह्न UTC
   1995-12-22T09:05:02 = शुक्रवार 22 दिसम्बर 1995 9:05:02 पूर्वाह्न UTC
  -0010-12-22T23:05:02 = शनिवार 22 दिसम्बर -010 11:05:02 अपराह्न UTC

=head3 Long

   2008-02-05T12:30:30 = 5 फरवरी 2008 12:30:30 अपराह्न UTC
   1995-12-22T09:05:02 = 22 दिसम्बर 1995 9:05:02 पूर्वाह्न UTC
  -0010-12-22T23:05:02 = 22 दिसम्बर -010 11:05:02 अपराह्न UTC

=head3 Medium

   2008-02-05T12:30:30 = 05-02-2008 12:30:30 अपराह्न
   1995-12-22T09:05:02 = 22-12-1995 9:05:02 पूर्वाह्न
  -0010-12-22T23:05:02 = 22-12--010 11:05:02 अपराह्न

=head3 Short

   2008-02-05T12:30:30 = 5-2-8 12:30 अपराह्न
   1995-12-22T09:05:02 = 22-12-95 9:05 पूर्वाह्न
  -0010-12-22T23:05:02 = 22-12-10 11:05 अपराह्न

=head3 Default

   2008-02-05T12:30:30 = 05-02-2008 12:30:30 अपराह्न
   1995-12-22T09:05:02 = 22-12-1995 9:05:02 पूर्वाह्न
  -0010-12-22T23:05:02 = 22-12--010 11:05:02 अपराह्न

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = मंगल 5
   1995-12-22T09:05:02 = शुक्र 22
  -0010-12-22T23:05:02 = शनि 22

=head3 GGGGyMMMMEEEEdd (EEEE,dd MMMM GGGGy)

   2008-02-05T12:30:30 = मंगलवार,05 फरवरी CE2008
   1995-12-22T09:05:02 = शुक्रवार,22 दिसम्बर CE1995
  -0010-12-22T23:05:02 = शनिवार,22 दिसम्बर BCE-10

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-12-22T23:05:02 = 23

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = मंगल फरवरी 5
   1995-12-22T09:05:02 = शुक्र दिसम्बर 22
  -0010-12-22T23:05:02 = शनि दिसम्बर 22

=head3 MMMMd (d MMMM)

   2008-02-05T12:30:30 = 5 फरवरी
   1995-12-22T09:05:02 = 22 दिसम्बर
  -0010-12-22T23:05:02 = 22 दिसम्बर

=head3 MMMdd (MMM dd)

   2008-02-05T12:30:30 = फरवरी 05
   1995-12-22T09:05:02 = दिसम्बर 22
  -0010-12-22T23:05:02 = दिसम्बर 22

=head3 MMdd (dd-MM)

   2008-02-05T12:30:30 = 05-02
   1995-12-22T09:05:02 = 22-12
  -0010-12-22T23:05:02 = 22-12

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-12-22T23:05:02 = 12-22

=head3 hhmm (hh:mm a)

   2008-02-05T12:30:30 = 12:30 अपराह्न
   1995-12-22T09:05:02 = 09:05 पूर्वाह्न
  -0010-12-22T23:05:02 = 11:05 अपराह्न

=head3 hhmmss (hh:mm:ss a)

   2008-02-05T12:30:30 = 12:30:30 अपराह्न
   1995-12-22T09:05:02 = 09:05:02 पूर्वाह्न
  -0010-12-22T23:05:02 = 11:05:02 अपराह्न

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-12-22T23:05:02 = 05:02

=head3 yyMM (yy-MM)

   2008-02-05T12:30:30 = 8-02
   1995-12-22T09:05:02 = 95-12
  -0010-12-22T23:05:02 = 10-12

=head3 yyMMM (yy MMM)

   2008-02-05T12:30:30 = 8 फरवरी
   1995-12-22T09:05:02 = 95 दिसम्बर
  -0010-12-22T23:05:02 = 10 दिसम्बर

=head3 yyMMMEEEd (EEE, MMM d, yy)

   2008-02-05T12:30:30 = मंगल, फरवरी 5, 8
   1995-12-22T09:05:02 = शुक्र, दिसम्बर 22, 95
  -0010-12-22T23:05:02 = शनि, दिसम्बर 22, 10

=head3 yyMMMd (MMM d, yy)

   2008-02-05T12:30:30 = फरवरी 5, 8
   1995-12-22T09:05:02 = दिसम्बर 22, 95
  -0010-12-22T23:05:02 = दिसम्बर 22, 10

=head3 yyMMdd (dd-MM-yy)

   2008-02-05T12:30:30 = 05-02-8
   1995-12-22T09:05:02 = 22-12-95
  -0010-12-22T23:05:02 = 22-12-10

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-12-22T23:05:02 = 4 10

=head3 yyyy (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-12-22T23:05:02 = -010

=head3 yyyyMM (MM-yyyy)

   2008-02-05T12:30:30 = 02-2008
   1995-12-22T09:05:02 = 12-1995
  -0010-12-22T23:05:02 = 12--010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = फरवरी 2008
   1995-12-22T09:05:02 = दिसम्बर 1995
  -0010-12-22T23:05:02 = दिसम्बर -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

No

=head3 Local first day of the week

सोमवार


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
