###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file is_IS.xml
# The source file version number was 1.46, generated on
# 2007/07/19 22:31:39.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::is_IS;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::is';

{
    my $first_day_of_week = 7;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::is_IS

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'is_IS' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Icelandic Iceland.

=head1 DATA

This locale inherits from the L<DateTime::Locale::is> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  mánudagur
  þriðjudagur
  miðvikudagur
  fimmtudagur
  föstudagur
  laugardagur
  sunnudagur

=head3 Abbreviated (format)

  mán
  þri
  mið
  fim
  fös
  lau
  sun

=head3 Narrow (format)

  m
  þ
  m
  f
  f
  l
  s

=head3 Wide (stand-alone)

  mánudagur
  þriðjudagur
  miðvikudagur
  fimmtudagur
  föstudagur
  laugardagur
  sunnudagur

=head3 Abbreviated (stand-alone)

  mán
  þri
  mið
  fim
  fös
  lau
  sun

=head3 Narrow (stand-alone)

  m
  þ
  m
  f
  f
  l
  s

=head2 Months

=head3 Wide (format)

  janúar
  febrúar
  mars
  apríl
  maí
  júní
  júlí
  ágúst
  september
  október
  nóvember
  desember

=head3 Abbreviated (format)

  jan
  feb
  mar
  apr
  maí
  jún
  júl
  ágú
  sep
  okt
  nóv
  des

=head3 Narrow (format)

  j
  f
  m
  a
  m
  j
  j
  á
  s
  o
  n
  d

=head3 Wide (stand-alone)

  janúar
  febrúar
  mars
  apríl
  maí
  júní
  júlí
  ágúst
  september
  október
  nóvember
  desember

=head3 Abbreviated (stand-alone)

  jan
  feb
  mar
  apr
  maí
  jún
  júl
  ágú
  sep
  okt
  nóv
  des

=head3 Narrow (stand-alone)

  j
  f
  m
  a
  m
  j
  j
  á
  s
  o
  n
  d

=head2 Quarters

=head3 Wide (format)

  1st fjórðungur
  2nd fjórðungur
  3rd fjórðungur
  4th fjórðungur

=head3 Abbreviated (format)

  F1
  F2
  F3
  F4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  1st fjórðungur
  2nd fjórðungur
  3rd fjórðungur
  4th fjórðungur

=head3 Abbreviated (stand-alone)

  F1
  F2
  F3
  F4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  BCE
  CE

=head3 Abbreviated

  BCE
  CE

=head3 Narrow

  BCE
  CE

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = þriðjudagur, 5. febrúar 2008
   1995-12-22T09:05:02 = föstudagur, 22. desember 1995
  -0010-12-22T23:05:02 = laugardagur, 22. desember -010

=head3 Long

   2008-02-05T12:30:30 = 5. febrúar 2008
   1995-12-22T09:05:02 = 22. desember 1995
  -0010-12-22T23:05:02 = 22. desember -010

=head3 Medium

   2008-02-05T12:30:30 = 5.2.2008
   1995-12-22T09:05:02 = 22.12.1995
  -0010-12-22T23:05:02 = 22.12.-010

=head3 Short

   2008-02-05T12:30:30 = 5.2.2008
   1995-12-22T09:05:02 = 22.12.1995
  -0010-12-22T23:05:02 = 22.12.-010

=head3 Default

   2008-02-05T12:30:30 = 5.2.2008
   1995-12-22T09:05:02 = 22.12.1995
  -0010-12-22T23:05:02 = 22.12.-010

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = þriðjudagur, 5. febrúar 2008 12:30:30 UTC
   1995-12-22T09:05:02 = föstudagur, 22. desember 1995 09:05:02 UTC
  -0010-12-22T23:05:02 = laugardagur, 22. desember -010 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 5. febrúar 2008 12:30:30 UTC
   1995-12-22T09:05:02 = 22. desember 1995 09:05:02 UTC
  -0010-12-22T23:05:02 = 22. desember -010 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 5.2.2008 12:30:30
   1995-12-22T09:05:02 = 22.12.1995 09:05:02
  -0010-12-22T23:05:02 = 22.12.-010 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 5.2.2008 12:30
   1995-12-22T09:05:02 = 22.12.1995 09:05
  -0010-12-22T23:05:02 = 22.12.-010 23:05

=head3 Default

   2008-02-05T12:30:30 = 5.2.2008 12:30:30
   1995-12-22T09:05:02 = 22.12.1995 09:05:02
  -0010-12-22T23:05:02 = 22.12.-010 23:05:02

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = þri 5
   1995-12-22T09:05:02 = fös 22
  -0010-12-22T23:05:02 = lau 22

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-12-22T23:05:02 = 23

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = þri feb 5
   1995-12-22T09:05:02 = fös des 22
  -0010-12-22T23:05:02 = lau des 22

=head3 MMMMd (d. MMMM)

   2008-02-05T12:30:30 = 5. febrúar
   1995-12-22T09:05:02 = 22. desember
  -0010-12-22T23:05:02 = 22. desember

=head3 Md (d.M)

   2008-02-05T12:30:30 = 5.2
   1995-12-22T09:05:02 = 22.12
  -0010-12-22T23:05:02 = 22.12

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-12-22T23:05:02 = 05:02

=head3 yyMM (yy-MM)

   2008-02-05T12:30:30 = 8-02
   1995-12-22T09:05:02 = 95-12
  -0010-12-22T23:05:02 = 10-12

=head3 yyMMM (yy MMM)

   2008-02-05T12:30:30 = 8 feb
   1995-12-22T09:05:02 = 95 des
  -0010-12-22T23:05:02 = 10 des

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-12-22T23:05:02 = 4 10

=head3 yyyy (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-12-22T23:05:02 = -010

=head3 yyyyM (M.yyyy)

   2008-02-05T12:30:30 = 2.2008
   1995-12-22T09:05:02 = 12.1995
  -0010-12-22T23:05:02 = 12.-010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = febrúar 2008
   1995-12-22T09:05:02 = desember 1995
  -0010-12-22T23:05:02 = desember -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

sunnudagur


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
