###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file it.xml
# The source file version number was 1.93, generated on
# 2007/11/14 16:26:58.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::it;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::root';

{
    my $am_pm_abbreviated = [ "m\.", "p\." ];
    sub am_pm_abbreviated { return $am_pm_abbreviated }
}
{
    my $date_format_full = "EEEE\ d\ MMMM\ yyyy";
    sub date_format_full { return $date_format_full }
}

{
    my $date_format_long = "dd\ MMMM\ yyyy";
    sub date_format_long { return $date_format_long }
}

{
    my $date_format_medium = "dd\/MMM\/yyyy";
    sub date_format_medium { return $date_format_medium }
}

{
    my $date_format_short = "dd\/MM\/yy";
    sub date_format_short { return $date_format_short }
}

{
    my $datetime_format = "\{1\}\ \{0\}";
    sub datetime_format { return $datetime_format }
}

{
    my $day_format_abbreviated = [ "lun", "mar", "mer", "gio", "ven", "sab", "dom" ];
    sub day_format_abbreviated { return $day_format_abbreviated }
}

sub day_format_narrow { $_[0]->day_stand_alone_narrow() }

{
    my $day_format_wide = [ "lunedì", "martedì", "mercoledì", "giovedì", "venerdì", "sabato", "domenica" ];
    sub day_format_wide { return $day_format_wide }
}

sub day_stand_alone_abbreviated { $_[0]->day_format_abbreviated() }

{
    my $day_stand_alone_narrow = [ "L", "M", "M", "G", "V", "S", "D" ];
    sub day_stand_alone_narrow { return $day_stand_alone_narrow }
}

sub day_stand_alone_wide { $_[0]->day_format_wide() }

{
    my $era_abbreviated = [ "aC", "dC" ];
    sub era_abbreviated { return $era_abbreviated }
}

sub era_narrow { $_[0]->era_abbreviated() }

{
    my $era_wide = [ "A\.C\.", "D\.C\." ];
    sub era_wide { return $era_wide }
}
{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

{
    my $month_format_abbreviated = [ "gen", "feb", "mar", "apr", "mag", "giu", "lug", "ago", "set", "ott", "nov", "dic" ];
    sub month_format_abbreviated { return $month_format_abbreviated }
}

sub month_format_narrow { $_[0]->month_stand_alone_narrow() }

{
    my $month_format_wide = [ "gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno", "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre" ];
    sub month_format_wide { return $month_format_wide }
}

sub month_stand_alone_abbreviated { $_[0]->month_format_abbreviated() }

{
    my $month_stand_alone_narrow = [ "G", "F", "M", "A", "M", "G", "L", "A", "S", "O", "N", "D" ];
    sub month_stand_alone_narrow { return $month_stand_alone_narrow }
}

sub month_stand_alone_wide { $_[0]->month_format_wide() }

{
    my $quarter_format_abbreviated = [ "T1", "T2", "T3", "T4" ];
    sub quarter_format_abbreviated { return $quarter_format_abbreviated }
}
{
    my $quarter_format_wide = [ "1o\ trimestre", "2o\ trimestre", "3o\ trimestre", "4o\ trimestre" ];
    sub quarter_format_wide { return $quarter_format_wide }
}

sub quarter_stand_alone_abbreviated { $_[0]->quarter_format_abbreviated() }


sub quarter_stand_alone_wide { $_[0]->quarter_format_wide() }

{
    my $time_format_full = "HH\:mm\:ss\ v";
    sub time_format_full { return $time_format_full }
}

{
    my $time_format_long = "HH\:mm\:ss\ z";
    sub time_format_long { return $time_format_long }
}

{
    my $time_format_medium = "HH\:mm\:ss";
    sub time_format_medium { return $time_format_medium }
}

{
    my $time_format_short = "HH\:mm";
    sub time_format_short { return $time_format_short }
}

{
    my $_format_for_HHmm = "HH\.mm";
    sub _format_for_HHmm { return $_format_for_HHmm }
}

{
    my $_format_for_HHmmss = "HH\.mm\.ss";
    sub _format_for_HHmmss { return $_format_for_HHmmss }
}

{
    my $_format_for_MMMMdd = "dd\ MMMM";
    sub _format_for_MMMMdd { return $_format_for_MMMMdd }
}

{
    my $_format_for_MMdd = "dd\/MM";
    sub _format_for_MMdd { return $_format_for_MMdd }
}

{
    my $_format_for_hhmm = "hh\.mm\ a";
    sub _format_for_hhmm { return $_format_for_hhmm }
}

{
    my $_format_for_hhmmss = "hh\.mm\.ss\ a";
    sub _format_for_hhmmss { return $_format_for_hhmmss }
}

{
    my $_format_for_yyMM = "MM\/yy";
    sub _format_for_yyMM { return $_format_for_yyMM }
}

{
    my $_format_for_yyQ = "Q\ yy";
    sub _format_for_yyQ { return $_format_for_yyQ }
}

{
    my $_format_for_yyQQQQ = "QQQQ\ yy";
    sub _format_for_yyQQQQ { return $_format_for_yyQQQQ }
}

{
    my $_format_for_yyyyMMMM = "MMMM\ yyyy";
    sub _format_for_yyyyMMMM { return $_format_for_yyyyMMMM }
}

{
    my $_available_formats =
        {
          "HHmm" => "HH\.mm",
          "HHmmss" => "HH\.mm\.ss",
          "MMMMdd" => "dd\ MMMM",
          "MMdd" => "dd\/MM",
          "hhmm" => "hh\.mm\ a",
          "hhmmss" => "hh\.mm\.ss\ a",
          "yyMM" => "MM\/yy",
          "yyQ" => "Q\ yy",
          "yyQQQQ" => "QQQQ\ yy",
          "yyyyMMMM" => "MMMM\ yyyy"
        };
    sub _available_formats { return $_available_formats }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::it

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'it' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Italian.

=head1 DATA

This locale inherits from the L<DateTime::Locale::root> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  lunedì
  martedì
  mercoledì
  giovedì
  venerdì
  sabato
  domenica

=head3 Abbreviated (format)

  lun
  mar
  mer
  gio
  ven
  sab
  dom

=head3 Narrow (format)

  L
  M
  M
  G
  V
  S
  D

=head3 Wide (stand-alone)

  lunedì
  martedì
  mercoledì
  giovedì
  venerdì
  sabato
  domenica

=head3 Abbreviated (stand-alone)

  lun
  mar
  mer
  gio
  ven
  sab
  dom

=head3 Narrow (stand-alone)

  L
  M
  M
  G
  V
  S
  D

=head2 Months

=head3 Wide (format)

  gennaio
  febbraio
  marzo
  aprile
  maggio
  giugno
  luglio
  agosto
  settembre
  ottobre
  novembre
  dicembre

=head3 Abbreviated (format)

  gen
  feb
  mar
  apr
  mag
  giu
  lug
  ago
  set
  ott
  nov
  dic

=head3 Narrow (format)

  G
  F
  M
  A
  M
  G
  L
  A
  S
  O
  N
  D

=head3 Wide (stand-alone)

  gennaio
  febbraio
  marzo
  aprile
  maggio
  giugno
  luglio
  agosto
  settembre
  ottobre
  novembre
  dicembre

=head3 Abbreviated (stand-alone)

  gen
  feb
  mar
  apr
  mag
  giu
  lug
  ago
  set
  ott
  nov
  dic

=head3 Narrow (stand-alone)

  G
  F
  M
  A
  M
  G
  L
  A
  S
  O
  N
  D

=head2 Quarters

=head3 Wide (format)

  1o trimestre
  2o trimestre
  3o trimestre
  4o trimestre

=head3 Abbreviated (format)

  T1
  T2
  T3
  T4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  1o trimestre
  2o trimestre
  3o trimestre
  4o trimestre

=head3 Abbreviated (stand-alone)

  T1
  T2
  T3
  T4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  A.C.
  D.C.

=head3 Abbreviated

  aC
  dC

=head3 Narrow

  aC
  dC

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = martedì 5 febbraio 2008
   1995-12-22T09:05:02 = venerdì 22 dicembre 1995
  -0010-12-22T23:05:02 = sabato 22 dicembre -010

=head3 Long

   2008-02-05T12:30:30 = 05 febbraio 2008
   1995-12-22T09:05:02 = 22 dicembre 1995
  -0010-12-22T23:05:02 = 22 dicembre -010

=head3 Medium

   2008-02-05T12:30:30 = 05/feb/2008
   1995-12-22T09:05:02 = 22/dic/1995
  -0010-12-22T23:05:02 = 22/dic/-010

=head3 Short

   2008-02-05T12:30:30 = 05/02/8
   1995-12-22T09:05:02 = 22/12/95
  -0010-12-22T23:05:02 = 22/12/10

=head3 Default

   2008-02-05T12:30:30 = 05/feb/2008
   1995-12-22T09:05:02 = 22/dic/1995
  -0010-12-22T23:05:02 = 22/dic/-010

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = martedì 5 febbraio 2008 12:30:30 UTC
   1995-12-22T09:05:02 = venerdì 22 dicembre 1995 09:05:02 UTC
  -0010-12-22T23:05:02 = sabato 22 dicembre -010 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 05 febbraio 2008 12:30:30 UTC
   1995-12-22T09:05:02 = 22 dicembre 1995 09:05:02 UTC
  -0010-12-22T23:05:02 = 22 dicembre -010 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 05/feb/2008 12:30:30
   1995-12-22T09:05:02 = 22/dic/1995 09:05:02
  -0010-12-22T23:05:02 = 22/dic/-010 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 05/02/8 12:30
   1995-12-22T09:05:02 = 22/12/95 09:05
  -0010-12-22T23:05:02 = 22/12/10 23:05

=head3 Default

   2008-02-05T12:30:30 = 05/feb/2008 12:30:30
   1995-12-22T09:05:02 = 22/dic/1995 09:05:02
  -0010-12-22T23:05:02 = 22/dic/-010 23:05:02

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = mar 5
   1995-12-22T09:05:02 = ven 22
  -0010-12-22T23:05:02 = sab 22

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-12-22T23:05:02 = 23

=head3 HHmm (HH.mm)

   2008-02-05T12:30:30 = 12.30
   1995-12-22T09:05:02 = 09.05
  -0010-12-22T23:05:02 = 23.05

=head3 HHmmss (HH.mm.ss)

   2008-02-05T12:30:30 = 12.30.30
   1995-12-22T09:05:02 = 09.05.02
  -0010-12-22T23:05:02 = 23.05.02

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = mar feb 5
   1995-12-22T09:05:02 = ven dic 22
  -0010-12-22T23:05:02 = sab dic 22

=head3 MMMMd (MMMM d)

   2008-02-05T12:30:30 = febbraio 5
   1995-12-22T09:05:02 = dicembre 22
  -0010-12-22T23:05:02 = dicembre 22

=head3 MMMMdd (dd MMMM)

   2008-02-05T12:30:30 = 05 febbraio
   1995-12-22T09:05:02 = 22 dicembre
  -0010-12-22T23:05:02 = 22 dicembre

=head3 MMdd (dd/MM)

   2008-02-05T12:30:30 = 05/02
   1995-12-22T09:05:02 = 22/12
  -0010-12-22T23:05:02 = 22/12

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-12-22T23:05:02 = 12-22

=head3 hhmm (hh.mm a)

   2008-02-05T12:30:30 = 12.30 p.
   1995-12-22T09:05:02 = 09.05 m.
  -0010-12-22T23:05:02 = 11.05 p.

=head3 hhmmss (hh.mm.ss a)

   2008-02-05T12:30:30 = 12.30.30 p.
   1995-12-22T09:05:02 = 09.05.02 m.
  -0010-12-22T23:05:02 = 11.05.02 p.

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-12-22T23:05:02 = 05:02

=head3 yyMM (MM/yy)

   2008-02-05T12:30:30 = 02/8
   1995-12-22T09:05:02 = 12/95
  -0010-12-22T23:05:02 = 12/10

=head3 yyMMM (yy MMM)

   2008-02-05T12:30:30 = 8 feb
   1995-12-22T09:05:02 = 95 dic
  -0010-12-22T23:05:02 = 10 dic

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-12-22T23:05:02 = 4 10

=head3 yyQQQQ (QQQQ yy)

   2008-02-05T12:30:30 = 1o trimestre 8
   1995-12-22T09:05:02 = 4o trimestre 95
  -0010-12-22T23:05:02 = 4o trimestre 10

=head3 yyyy (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-12-22T23:05:02 = -010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = febbraio 2008
   1995-12-22T09:05:02 = dicembre 1995
  -0010-12-22T23:05:02 = dicembre -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

lunedì


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
