###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file kfo_NG.xml
# The source file version number was 1.12, generated on
# 2007/07/19 22:31:39.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::kfo_NG;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::kfo';

{
    my $first_day_of_week = 7;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::kfo_NG

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'kfo_NG' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Koro Nigeria.

=head1 DATA

This locale inherits from the L<DateTime::Locale::kfo> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  Je-Kubacha
  Je-Gbai
  Tansati
  Je-Yei
  Je-Koye
  Sati
  Lahadi

=head3 Abbreviated (format)

  Kub
  Gba
  Tan
  Yei
  Koy
  Sat
  Lah

=head3 Narrow (format)

  2
  3
  4
  5
  6
  7
  1

=head3 Wide (stand-alone)

  Je-Kubacha
  Je-Gbai
  Tansati
  Je-Yei
  Je-Koye
  Sati
  Lahadi

=head3 Abbreviated (stand-alone)

  Kub
  Gba
  Tan
  Yei
  Koy
  Sat
  Lah

=head3 Narrow (stand-alone)

  2
  3
  4
  5
  6
  7
  1

=head2 Months

=head3 Wide (format)

  Fai Weyene
  Fai Fani
  Fai Tataka
  Fai Nangra
  Fai Tuyo
  Fai Tsoyi
  Fai Tafaka
  Fai Warachi
  Fai Kunobok
  Fai Bansok
  Fai Kom
  Fai Sauk

=head3 Abbreviated (format)

  Wey
  Fan
  Tat
  Nan
  Tuy
  Tso
  Taf
  War
  Kun
  Ban
  Kom
  Sau

=head3 Narrow (format)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head3 Wide (stand-alone)

  Fai Weyene
  Fai Fani
  Fai Tataka
  Fai Nangra
  Fai Tuyo
  Fai Tsoyi
  Fai Tafaka
  Fai Warachi
  Fai Kunobok
  Fai Bansok
  Fai Kom
  Fai Sauk

=head3 Abbreviated (stand-alone)

  Wey
  Fan
  Tat
  Nan
  Tuy
  Tso
  Taf
  War
  Kun
  Ban
  Kom
  Sau

=head3 Narrow (stand-alone)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head2 Quarters

=head3 Wide (format)

  Q1
  Q2
  Q3
  Q4

=head3 Abbreviated (format)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  Q1
  Q2
  Q3
  Q4

=head3 Abbreviated (stand-alone)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  Kafi Mar Wenom
  Bayan Chi Wenom

=head3 Abbreviated

  KMW
  BCW

=head3 Narrow

  KMW
  BCW

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = Je-Gbai, 2008 Fai Fani 05
   1995-12-22T09:05:02 = Je-Koye, 1995 Fai Sauk 22
  -0010-12-22T23:05:02 = Sati, -010 Fai Sauk 22

=head3 Long

   2008-02-05T12:30:30 = 2008 Fai Fani 5
   1995-12-22T09:05:02 = 1995 Fai Sauk 22
  -0010-12-22T23:05:02 = -010 Fai Sauk 22

=head3 Medium

   2008-02-05T12:30:30 = 2008 Fan 5
   1995-12-22T09:05:02 = 1995 Sau 22
  -0010-12-22T23:05:02 = -010 Sau 22

=head3 Short

   2008-02-05T12:30:30 = 8/02/05
   1995-12-22T09:05:02 = 95/12/22
  -0010-12-22T23:05:02 = 10/12/22

=head3 Default

   2008-02-05T12:30:30 = 2008 Fan 5
   1995-12-22T09:05:02 = 1995 Sau 22
  -0010-12-22T23:05:02 = -010 Sau 22

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = Je-Gbai, 2008 Fai Fani 05 12:30:30 UTC
   1995-12-22T09:05:02 = Je-Koye, 1995 Fai Sauk 22 09:05:02 UTC
  -0010-12-22T23:05:02 = Sati, -010 Fai Sauk 22 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 2008 Fai Fani 5 12:30:30 UTC
   1995-12-22T09:05:02 = 1995 Fai Sauk 22 09:05:02 UTC
  -0010-12-22T23:05:02 = -010 Fai Sauk 22 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 2008 Fan 5 12:30:30
   1995-12-22T09:05:02 = 1995 Sau 22 09:05:02
  -0010-12-22T23:05:02 = -010 Sau 22 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 8/02/05 12:30
   1995-12-22T09:05:02 = 95/12/22 09:05
  -0010-12-22T23:05:02 = 10/12/22 23:05

=head3 Default

   2008-02-05T12:30:30 = 2008 Fan 5 12:30:30
   1995-12-22T09:05:02 = 1995 Sau 22 09:05:02
  -0010-12-22T23:05:02 = -010 Sau 22 23:05:02

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = Gba 5
   1995-12-22T09:05:02 = Koy 22
  -0010-12-22T23:05:02 = Sat 22

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-12-22T23:05:02 = 23

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = Gba Fan 5
   1995-12-22T09:05:02 = Koy Sau 22
  -0010-12-22T23:05:02 = Sat Sau 22

=head3 MMMMd (MMMM d)

   2008-02-05T12:30:30 = Fai Fani 5
   1995-12-22T09:05:02 = Fai Sauk 22
  -0010-12-22T23:05:02 = Fai Sauk 22

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-12-22T23:05:02 = 12-22

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-12-22T23:05:02 = 05:02

=head3 yyMM (yy-MM)

   2008-02-05T12:30:30 = 8-02
   1995-12-22T09:05:02 = 95-12
  -0010-12-22T23:05:02 = 10-12

=head3 yyMMM (yy MMM)

   2008-02-05T12:30:30 = 8 Fan
   1995-12-22T09:05:02 = 95 Sau
  -0010-12-22T23:05:02 = 10 Sau

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-12-22T23:05:02 = 4 10

=head3 yyyy (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-12-22T23:05:02 = -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

Lahadi


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
