###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file ml_IN.xml
# The source file version number was 1.33, generated on
# 2007/07/19 22:31:39.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::ml_IN;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::ml';

{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::ml_IN

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'ml_IN' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Malayalam India.

=head1 DATA

This locale inherits from the L<DateTime::Locale::ml> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  തിങ്കള്‍
  ചൊവ്വ
  ബുധന്‍
  വ്യാഴം
  വെള്ളി
  ശനി
  ഞായര്‍

=head3 Abbreviated (format)

  തി
  ചൊ
  ബു
  വ്യാ
  വെ
  ശ
  ഞാ

=head3 Narrow (format)

  ത
  ച
  ബ
  വ
  വ
  ശ
  ഞ

=head3 Wide (stand-alone)

  തിങ്കള്‍
  ചൊവ്വ
  ബുധന്‍
  വ്യാഴം
  വെള്ളി
  ശനി
  ഞായര്‍

=head3 Abbreviated (stand-alone)

  തി
  ചൊ
  ബു
  വ്യാ
  വെ
  ശ
  ഞാ

=head3 Narrow (stand-alone)

  ത
  ച
  ബ
  വ
  വ
  ശ
  ഞ

=head2 Months

=head3 Wide (format)

  ജനുവരി
  ഫെബ്രുവരി
  മാര്‍ച്ച്
  ഏപ്രില്‍
  മെയ്
  ജൂണ്‍
  ജൂലൈ
  ആഗസ്ത്
  സെപ്തംബര്‍
  ഒക്ടോബര്‍
  നവംബര്‍
  ഡിസംബര്‍

=head3 Abbreviated (format)

  ജനു
  ഫെബ്രു
  മാര്‍
  ഏപ്രി
  മെയ്
  ജൂണ്‍
  ജൂലൈ
  ആഗ
  സെപ്തം
  ഒക്ടോ
  നവം
  ഡിസം

=head3 Narrow (format)

  ജ
  ഫ
  മ
  ഏ
  മ
  ജ
  ജ
  ആ
  സ
  ഒ
  ന
  ഡ

=head3 Wide (stand-alone)

  ജനുവരി
  ഫെബ്രുവരി
  മാര്‍ച്ച്
  ഏപ്രില്‍
  മെയ്
  ജൂണ്‍
  ജൂലൈ
  ആഗസ്ത്
  സെപ്തംബര്‍
  ഒക്ടോബര്‍
  നവംബര്‍
  ഡിസംബര്‍

=head3 Abbreviated (stand-alone)

  ജനു
  ഫെബ്രു
  മാര്‍
  ഏപ്രി
  മെയ്
  ജൂണ്‍
  ജൂലൈ
  ആഗ
  സെപ്തം
  ഒക്ടോ
  നവം
  ഡിസം

=head3 Narrow (stand-alone)

  ജ
  ഫ
  മ
  ഏ
  മ
  ജ
  ജ
  ആ
  സ
  ഒ
  ന
  ഡ

=head2 Quarters

=head3 Wide (format)

  ഒന്നാം പാദം
  രണ്ടാം പാദം
  മൂന്നാം പാദം
  നാലാം പാദം

=head3 Abbreviated (format)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  ഒന്നാം പാദം
  രണ്ടാം പാദം
  മൂന്നാം പാദം
  നാലാം പാദം

=head3 Abbreviated (stand-alone)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  ക്രിസ്തുവിനു് മുമ്പ്‌
  ക്രിസ്തുവിനു് പിമ്പ്

=head3 Abbreviated

  ക്രി.മു.
  ക്രി.പി.

=head3 Narrow

  ക്രി.മു.
  ക്രി.പി.

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = 2008, ഫെബ്രുവരി 5, ചൊവ്വ
   1995-12-22T09:05:02 = 1995, ഡിസംബര്‍ 22, വെള്ളി
  -0010-12-22T23:05:02 = -010, ഡിസംബര്‍ 22, ശനി

=head3 Long

   2008-02-05T12:30:30 = 2008, ഫെബ്രുവരി 5
   1995-12-22T09:05:02 = 1995, ഡിസംബര്‍ 22
  -0010-12-22T23:05:02 = -010, ഡിസംബര്‍ 22

=head3 Medium

   2008-02-05T12:30:30 = 2008, ഫെബ്രു 5
   1995-12-22T09:05:02 = 1995, ഡിസം 22
  -0010-12-22T23:05:02 = -010, ഡിസം 22

=head3 Short

   2008-02-05T12:30:30 = 05-02-8
   1995-12-22T09:05:02 = 22-12-95
  -0010-12-22T23:05:02 = 22-12-10

=head3 Default

   2008-02-05T12:30:30 = 2008, ഫെബ്രു 5
   1995-12-22T09:05:02 = 1995, ഡിസം 22
  -0010-12-22T23:05:02 = -010, ഡിസം 22

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 വൈകുന്നേരം UTC
   1995-12-22T09:05:02 = 9:05:02 രാവിലെ UTC
  -0010-12-22T23:05:02 = 11:05:02 വൈകുന്നേരം UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 വൈകുന്നേരം UTC
   1995-12-22T09:05:02 = 9:05:02 രാവിലെ UTC
  -0010-12-22T23:05:02 = 11:05:02 വൈകുന്നേരം UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30 വൈകുന്നേരം
   1995-12-22T09:05:02 = 9:05:02 രാവിലെ
  -0010-12-22T23:05:02 = 11:05:02 വൈകുന്നേരം

=head3 Short

   2008-02-05T12:30:30 = 12:30 വൈകുന്നേരം
   1995-12-22T09:05:02 = 9:05 രാവിലെ
  -0010-12-22T23:05:02 = 11:05 വൈകുന്നേരം

=head3 Default

   2008-02-05T12:30:30 = 12:30:30 വൈകുന്നേരം
   1995-12-22T09:05:02 = 9:05:02 രാവിലെ
  -0010-12-22T23:05:02 = 11:05:02 വൈകുന്നേരം

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = 2008, ഫെബ്രുവരി 5, ചൊവ്വ 12:30:30 വൈകുന്നേരം UTC
   1995-12-22T09:05:02 = 1995, ഡിസംബര്‍ 22, വെള്ളി 9:05:02 രാവിലെ UTC
  -0010-12-22T23:05:02 = -010, ഡിസംബര്‍ 22, ശനി 11:05:02 വൈകുന്നേരം UTC

=head3 Long

   2008-02-05T12:30:30 = 2008, ഫെബ്രുവരി 5 12:30:30 വൈകുന്നേരം UTC
   1995-12-22T09:05:02 = 1995, ഡിസംബര്‍ 22 9:05:02 രാവിലെ UTC
  -0010-12-22T23:05:02 = -010, ഡിസംബര്‍ 22 11:05:02 വൈകുന്നേരം UTC

=head3 Medium

   2008-02-05T12:30:30 = 2008, ഫെബ്രു 5 12:30:30 വൈകുന്നേരം
   1995-12-22T09:05:02 = 1995, ഡിസം 22 9:05:02 രാവിലെ
  -0010-12-22T23:05:02 = -010, ഡിസം 22 11:05:02 വൈകുന്നേരം

=head3 Short

   2008-02-05T12:30:30 = 05-02-8 12:30 വൈകുന്നേരം
   1995-12-22T09:05:02 = 22-12-95 9:05 രാവിലെ
  -0010-12-22T23:05:02 = 22-12-10 11:05 വൈകുന്നേരം

=head3 Default

   2008-02-05T12:30:30 = 2008, ഫെബ്രു 5 12:30:30 വൈകുന്നേരം
   1995-12-22T09:05:02 = 1995, ഡിസം 22 9:05:02 രാവിലെ
  -0010-12-22T23:05:02 = -010, ഡിസം 22 11:05:02 വൈകുന്നേരം

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = ചൊ 5
   1995-12-22T09:05:02 = വെ 22
  -0010-12-22T23:05:02 = ശ 22

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-12-22T23:05:02 = 23

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = ചൊ ഫെബ്രു 5
   1995-12-22T09:05:02 = വെ ഡിസം 22
  -0010-12-22T23:05:02 = ശ ഡിസം 22

=head3 MMMMd (MMMM d)

   2008-02-05T12:30:30 = ഫെബ്രുവരി 5
   1995-12-22T09:05:02 = ഡിസംബര്‍ 22
  -0010-12-22T23:05:02 = ഡിസംബര്‍ 22

=head3 MMdd (dd-MM)

   2008-02-05T12:30:30 = 05-02
   1995-12-22T09:05:02 = 22-12
  -0010-12-22T23:05:02 = 22-12

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-12-22T23:05:02 = 12-22

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-12-22T23:05:02 = 05:02

=head3 yyMM (yy-MM)

   2008-02-05T12:30:30 = 8-02
   1995-12-22T09:05:02 = 95-12
  -0010-12-22T23:05:02 = 10-12

=head3 yyMMM (yy MMM)

   2008-02-05T12:30:30 = 8 ഫെബ്രു
   1995-12-22T09:05:02 = 95 ഡിസം
  -0010-12-22T23:05:02 = 10 ഡിസം

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-12-22T23:05:02 = 4 10

=head3 yyyy (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-12-22T23:05:02 = -010

=head3 yyyyMM (MM-yyyy)

   2008-02-05T12:30:30 = 02-2008
   1995-12-22T09:05:02 = 12-1995
  -0010-12-22T23:05:02 = 12--010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = ഫെബ്രുവരി 2008
   1995-12-22T09:05:02 = ഡിസംബര്‍ 1995
  -0010-12-22T23:05:02 = ഡിസംബര്‍ -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

No

=head3 Local first day of the week

തിങ്കള്‍


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
