###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file mr_IN.xml
# The source file version number was 1.54, generated on
# 2007/07/19 22:31:39.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::mr_IN;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::mr';

{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::mr_IN

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'mr_IN' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Marathi India.

=head1 DATA

This locale inherits from the L<DateTime::Locale::mr> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  सोमवार
  मंगळवार
  बुधवार
  गुरुवार
  शुक्रवार
  शनिवार
  रविवार

=head3 Abbreviated (format)

  सोम
  मंगळ
  बुध
  गुरु
  शुक्र
  शनि
  रवि

=head3 Narrow (format)

  2
  3
  4
  5
  6
  7
  1

=head3 Wide (stand-alone)

  सोमवार
  मंगळवार
  बुधवार
  गुरुवार
  शुक्रवार
  शनिवार
  रविवार

=head3 Abbreviated (stand-alone)

  सोम
  मंगळ
  बुध
  गुरु
  शुक्र
  शनि
  रवि

=head3 Narrow (stand-alone)

  2
  3
  4
  5
  6
  7
  1

=head2 Months

=head3 Wide (format)

  जानेवारी
  फेबृवारी
  मार्च
  एप्रिल
  मे
  जून
  जुलै
  ओगस्ट
  सेप्टेंबर
  ओक्टोबर
  नोव्हेंबर
  डिसेंबर

=head3 Abbreviated (format)

  जानेवारी
  फेबृवारी
  मार्च
  एप्रिल
  मे
  जून
  जुलै
  ओगस्ट
  सेप्टेंबर
  ओक्टोबर
  नोव्हेंबर
  डिसेंबर

=head3 Narrow (format)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head3 Wide (stand-alone)

  जानेवारी
  फेबृवारी
  मार्च
  एप्रिल
  मे
  जून
  जुलै
  ओगस्ट
  सेप्टेंबर
  ओक्टोबर
  नोव्हेंबर
  डिसेंबर

=head3 Abbreviated (stand-alone)

  जानेवारी
  फेबृवारी
  मार्च
  एप्रिल
  मे
  जून
  जुलै
  ओगस्ट
  सेप्टेंबर
  ओक्टोबर
  नोव्हेंबर
  डिसेंबर

=head3 Narrow (stand-alone)

  1
  2
  3
  4
  5
  6
  7
  8
  9
  10
  11
  12

=head2 Quarters

=head3 Wide (format)

  Q1
  Q2
  Q3
  Q4

=head3 Abbreviated (format)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  Q1
  Q2
  Q3
  Q4

=head3 Abbreviated (stand-alone)

  Q1
  Q2
  Q3
  Q4

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  BCE
  CE

=head3 Abbreviated

  ईसापूर्व
  सन

=head3 Narrow

  ईसापूर्व
  सन

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = मंगळवार 5 फेबृवारी 2008
   1995-12-22T09:05:02 = शुक्रवार 22 डिसेंबर 1995
  -0010-12-22T23:05:02 = शनिवार 22 डिसेंबर -010

=head3 Long

   2008-02-05T12:30:30 = 5 फेबृवारी 2008
   1995-12-22T09:05:02 = 22 डिसेंबर 1995
  -0010-12-22T23:05:02 = 22 डिसेंबर -010

=head3 Medium

   2008-02-05T12:30:30 = 05-02-2008
   1995-12-22T09:05:02 = 22-12-1995
  -0010-12-22T23:05:02 = 22-12--010

=head3 Short

   2008-02-05T12:30:30 = 5-2-8
   1995-12-22T09:05:02 = 22-12-95
  -0010-12-22T23:05:02 = 22-12-10

=head3 Default

   2008-02-05T12:30:30 = 05-02-2008
   1995-12-22T09:05:02 = 22-12-1995
  -0010-12-22T23:05:02 = 22-12--010

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 म.नं. UTC
   1995-12-22T09:05:02 = 9:05:02 म.पू. UTC
  -0010-12-22T23:05:02 = 11:05:02 म.नं. UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 म.नं. UTC
   1995-12-22T09:05:02 = 9:05:02 म.पू. UTC
  -0010-12-22T23:05:02 = 11:05:02 म.नं. UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30 म.नं.
   1995-12-22T09:05:02 = 9:05:02 म.पू.
  -0010-12-22T23:05:02 = 11:05:02 म.नं.

=head3 Short

   2008-02-05T12:30:30 = 12:30 म.नं.
   1995-12-22T09:05:02 = 9:05 म.पू.
  -0010-12-22T23:05:02 = 11:05 म.नं.

=head3 Default

   2008-02-05T12:30:30 = 12:30:30 म.नं.
   1995-12-22T09:05:02 = 9:05:02 म.पू.
  -0010-12-22T23:05:02 = 11:05:02 म.नं.

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = मंगळवार 5 फेबृवारी 2008 12:30:30 म.नं. UTC
   1995-12-22T09:05:02 = शुक्रवार 22 डिसेंबर 1995 9:05:02 म.पू. UTC
  -0010-12-22T23:05:02 = शनिवार 22 डिसेंबर -010 11:05:02 म.नं. UTC

=head3 Long

   2008-02-05T12:30:30 = 5 फेबृवारी 2008 12:30:30 म.नं. UTC
   1995-12-22T09:05:02 = 22 डिसेंबर 1995 9:05:02 म.पू. UTC
  -0010-12-22T23:05:02 = 22 डिसेंबर -010 11:05:02 म.नं. UTC

=head3 Medium

   2008-02-05T12:30:30 = 05-02-2008 12:30:30 म.नं.
   1995-12-22T09:05:02 = 22-12-1995 9:05:02 म.पू.
  -0010-12-22T23:05:02 = 22-12--010 11:05:02 म.नं.

=head3 Short

   2008-02-05T12:30:30 = 5-2-8 12:30 म.नं.
   1995-12-22T09:05:02 = 22-12-95 9:05 म.पू.
  -0010-12-22T23:05:02 = 22-12-10 11:05 म.नं.

=head3 Default

   2008-02-05T12:30:30 = 05-02-2008 12:30:30 म.नं.
   1995-12-22T09:05:02 = 22-12-1995 9:05:02 म.पू.
  -0010-12-22T23:05:02 = 22-12--010 11:05:02 म.नं.

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = मंगळ 5
   1995-12-22T09:05:02 = शुक्र 22
  -0010-12-22T23:05:02 = शनि 22

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-12-22T23:05:02 = 23

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = मंगळ फेबृवारी 5
   1995-12-22T09:05:02 = शुक्र डिसेंबर 22
  -0010-12-22T23:05:02 = शनि डिसेंबर 22

=head3 MMMMd (d MMMM)

   2008-02-05T12:30:30 = 5 फेबृवारी
   1995-12-22T09:05:02 = 22 डिसेंबर
  -0010-12-22T23:05:02 = 22 डिसेंबर

=head3 MMdd (dd-MM)

   2008-02-05T12:30:30 = 05-02
   1995-12-22T09:05:02 = 22-12
  -0010-12-22T23:05:02 = 22-12

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-12-22T23:05:02 = 12-22

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-12-22T23:05:02 = 05:02

=head3 yyMM (yy-MM)

   2008-02-05T12:30:30 = 8-02
   1995-12-22T09:05:02 = 95-12
  -0010-12-22T23:05:02 = 10-12

=head3 yyMMM (yy MMM)

   2008-02-05T12:30:30 = 8 फेबृवारी
   1995-12-22T09:05:02 = 95 डिसेंबर
  -0010-12-22T23:05:02 = 10 डिसेंबर

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-12-22T23:05:02 = 4 10

=head3 yyyy (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-12-22T23:05:02 = -010

=head3 yyyyMM (MM-yyyy)

   2008-02-05T12:30:30 = 02-2008
   1995-12-22T09:05:02 = 12-1995
  -0010-12-22T23:05:02 = 12--010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = फेबृवारी 2008
   1995-12-22T09:05:02 = डिसेंबर 1995
  -0010-12-22T23:05:02 = डिसेंबर -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

No

=head3 Local first day of the week

सोमवार


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
