###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file pl_PL.xml
# The source file version number was 1.46, generated on
# 2007/07/14 23:02:16.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::pl_PL;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::pl';

{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::pl_PL

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'pl_PL' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Polish Poland.

=head1 DATA

This locale inherits from the L<DateTime::Locale::pl> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  poniedziałek
  wtorek
  środa
  czwartek
  piątek
  sobota
  niedziela

=head3 Abbreviated (format)

  pon.
  wt.
  śr.
  czw.
  pt.
  sob.
  niedz.

=head3 Narrow (format)

  P
  W
  Ś
  C
  P
  S
  N

=head3 Wide (stand-alone)

  poniedziałek
  wtorek
  środa
  czwartek
  piątek
  sobota
  niedziela

=head3 Abbreviated (stand-alone)

  pon.
  wt.
  śr.
  czw.
  pt.
  sob.
  niedz.

=head3 Narrow (stand-alone)

  P
  W
  Ś
  C
  P
  S
  N

=head2 Months

=head3 Wide (format)

  stycznia
  lutego
  marca
  kwietnia
  maja
  czerwca
  lipca
  sierpnia
  września
  października
  listopada
  grudnia

=head3 Abbreviated (format)

  sty
  lut
  mar
  kwi
  maj
  cze
  lip
  sie
  wrz
  paź
  lis
  gru

=head3 Narrow (format)

  s
  l
  m
  k
  m
  c
  l
  s
  w
  p
  l
  g

=head3 Wide (stand-alone)

  styczeń
  luty
  marzec
  kwiecień
  maj
  czerwiec
  lipiec
  sierpień
  wrzesień
  październik
  listopad
  grudzień

=head3 Abbreviated (stand-alone)

  sty
  lut
  mar
  kwi
  maj
  cze
  lip
  sie
  wrz
  paź
  lis
  gru

=head3 Narrow (stand-alone)

  s
  l
  m
  k
  m
  c
  l
  s
  w
  p
  l
  g

=head2 Quarters

=head3 Wide (format)

  I kwartał
  II kwartał
  III kwartał
  IV kwartał

=head3 Abbreviated (format)

  K1
  K2
  K3
  K4

=head3 Narrow (format)

  1
  2
  3
  4

=head3 Wide (stand-alone)

  I kwartał
  II kwartał
  III kwartał
  IV kwartał

=head3 Abbreviated (stand-alone)

  1 kw.
  2 kw.
  3 kw.
  4 kw.

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  Przed Chrystusem
  Anno Domini

=head3 Abbreviated

  p.n.e.
  n.e.

=head3 Narrow

  p.n.e.
  n.e.

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = wtorek, 5 lutego 2008
   1995-12-22T09:05:02 = piątek, 22 grudnia 1995
  -0010-12-22T23:05:02 = sobota, 22 grudnia -010

=head3 Long

   2008-02-05T12:30:30 = 5 lutego 2008
   1995-12-22T09:05:02 = 22 grudnia 1995
  -0010-12-22T23:05:02 = 22 grudnia -010

=head3 Medium

   2008-02-05T12:30:30 = 2008-02-05
   1995-12-22T09:05:02 = 1995-12-22
  -0010-12-22T23:05:02 = -010-12-22

=head3 Short

   2008-02-05T12:30:30 = 8-02-05
   1995-12-22T09:05:02 = 95-12-22
  -0010-12-22T23:05:02 = 10-12-22

=head3 Default

   2008-02-05T12:30:30 = 2008-02-05
   1995-12-22T09:05:02 = 1995-12-22
  -0010-12-22T23:05:02 = -010-12-22

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = wtorek, 5 lutego 2008 12:30:30 UTC
   1995-12-22T09:05:02 = piątek, 22 grudnia 1995 09:05:02 UTC
  -0010-12-22T23:05:02 = sobota, 22 grudnia -010 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 5 lutego 2008 12:30:30 UTC
   1995-12-22T09:05:02 = 22 grudnia 1995 09:05:02 UTC
  -0010-12-22T23:05:02 = 22 grudnia -010 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 2008-02-05 12:30:30
   1995-12-22T09:05:02 = 1995-12-22 09:05:02
  -0010-12-22T23:05:02 = -010-12-22 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 8-02-05 12:30
   1995-12-22T09:05:02 = 95-12-22 09:05
  -0010-12-22T23:05:02 = 10-12-22 23:05

=head3 Default

   2008-02-05T12:30:30 = 2008-02-05 12:30:30
   1995-12-22T09:05:02 = 1995-12-22 09:05:02
  -0010-12-22T23:05:02 = -010-12-22 23:05:02

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = wt. 5
   1995-12-22T09:05:02 = pt. 22
  -0010-12-22T23:05:02 = sob. 22

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-12-22T23:05:02 = 23

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = wt. lut 5
   1995-12-22T09:05:02 = pt. gru 22
  -0010-12-22T23:05:02 = sob. gru 22

=head3 MMMMd (d MMMM)

   2008-02-05T12:30:30 = 5 lutego
   1995-12-22T09:05:02 = 22 grudnia
  -0010-12-22T23:05:02 = 22 grudnia

=head3 MMdd (MM-dd)

   2008-02-05T12:30:30 = 02-05
   1995-12-22T09:05:02 = 12-22
  -0010-12-22T23:05:02 = 12-22

=head3 Md (d.M)

   2008-02-05T12:30:30 = 5.2
   1995-12-22T09:05:02 = 22.12
  -0010-12-22T23:05:02 = 22.12

=head3 hhmm (hh:mm a)

   2008-02-05T12:30:30 = 12:30 PM
   1995-12-22T09:05:02 = 09:05 AM
  -0010-12-22T23:05:02 = 11:05 PM

=head3 hhmmss (hh:mm:ss a)

   2008-02-05T12:30:30 = 12:30:30 PM
   1995-12-22T09:05:02 = 09:05:02 AM
  -0010-12-22T23:05:02 = 11:05:02 PM

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-12-22T23:05:02 = 05:02

=head3 yyMM (MM/yy)

   2008-02-05T12:30:30 = 02/8
   1995-12-22T09:05:02 = 12/95
  -0010-12-22T23:05:02 = 12/10

=head3 yyMMM (MMM yy)

   2008-02-05T12:30:30 = lut 8
   1995-12-22T09:05:02 = gru 95
  -0010-12-22T23:05:02 = gru 10

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-12-22T23:05:02 = 4 10

=head3 yyyy (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-12-22T23:05:02 = -010

=head3 yyyyMM (yyyy-MM)

   2008-02-05T12:30:30 = 2008-02
   1995-12-22T09:05:02 = 1995-12
  -0010-12-22T23:05:02 = -010-12

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = lutego 2008
   1995-12-22T09:05:02 = grudnia 1995
  -0010-12-22T23:05:02 = grudnia -010

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

poniedziałek


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
