###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite time locale
# generator (0.01).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate_from_icu.
#
# This file as generated from the ICU XML locale data.  See the
# LICENSE.icu file included in this distribution for license details.
#
# This file was generated from the source file sr.xml.
# The source file version number was 2.0, generated on
# 2003-06-26.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::sr;

use strict;

BEGIN
{
    if ( $] >= 5.006 )
    {
        require utf8; utf8->import;
    }
}

use DateTime::Locale::root;

@DateTime::Locale::sr::ISA = qw(DateTime::Locale::root);

my @day_names = (
"понедељак",
"уторак",
"среда",
"четвртак",
"петак",
"субота",
"недеља",
);

my @day_abbreviations = (
"пон",
"уто",
"сре",
"чет",
"пет",
"суб",
"нед",
);

my @month_names = (
"јануар",
"фебруар",
"март",
"април",
"мај",
"јуни",
"јули",
"август",
"септембар",
"октобар",
"новембар",
"децембар",
);

my @month_abbreviations = (
"јан",
"феб",
"мар",
"апр",
"мај",
"јун",
"јул",
"авг",
"сеп",
"окт",
"нов",
"дец",
);

my @eras = (
"п\.\ н\.\ е\.",
"н\.\ е",
);

my %date_formats = (
"short" => "\%\{day\}\.\%\{month\}\.\%y\.",
"medium" => "\%d\.\%m\.\%\{ce_year\}\.",
"long" => "\%d\.\%m\.\%\{ce_year\}\.",
"full" => "\%A\,\ \%d\.\%B\.\%\{ce_year\}\.",
);

my %time_formats = (
"short" => "\%H\.\%M",
"medium" => "\%H\.\%M\.\%S",
"long" => "\%H\.\%M\.\%S\ \%\{time_zone_long_name\}",
"full" => "\%H\.\%M\.\%S\ \%\{time_zone_long_name\}",
);

my $date_before_time = "1";
my $default_date_format_length = "medium";
my $default_time_format_length = "medium";
my $date_parts_order = "dmy";


sub day_names                      { \@day_names                      }
sub day_abbreviations              { \@day_abbreviations              }
sub month_names                    { \@month_names                    }
sub month_abbreviations            { \@month_abbreviations            }
sub eras                           { \@eras                           }
sub date_formats                   { \%date_formats                   }
sub time_formats                   { \%time_formats                   }
sub date_before_time               { $date_before_time                }
sub _default_date_format_length    { $default_date_format_length      }
sub _default_time_format_length    { $default_time_format_length      }
sub date_parts_order               { $date_parts_order                }


1;

