###########################################################################
#
# This file is auto-generated by the Perl DateTime Suite locale
# generator (0.05).  This code generator comes with the
# DateTime::Locale distribution in the tools/ directory, and is called
# generate-from-cldr.
#
# This file as generated from the CLDR XML locale data.  See the
# LICENSE.cldr file included in this distribution for license details.
#
# This file was generated from the source file uk_UA.xml
# The source file version number was 1.42, generated on
# 2007/07/14 23:02:17.
#
# Do not edit this file directly.
#
###########################################################################

package DateTime::Locale::uk_UA;

use strict;
use warnings;
use utf8;

use base 'DateTime::Locale::uk';

{
    my $first_day_of_week = 1;
    sub first_day_of_week { return $first_day_of_week }
}

1;

__END__


=pod

=encoding utf8

=head1 NAME

DateTime::Locale::uk_UA

=head1 SYNOPSIS

  use DateTime;

  my $dt = DateTime->now( locale => 'uk_UA' );
  print $dt->month_name();

=head1 DESCRIPTION

This is the DateTime locale package for Ukrainian Ukraine.

=head1 DATA

This locale inherits from the L<DateTime::Locale::uk> locale.

It contains the following data.

=head2 Days

=head3 Wide (format)

  Понеділок
  Вівторок
  Середа
  Четвер
  Пʼятниця
  Субота
  Неділя

=head3 Abbreviated (format)

  Пн
  Вт
  Ср
  Чт
  Пт
  Сб
  Нд

=head3 Narrow (format)

  П
  В
  С
  Ч
  П
  С
  Н

=head3 Wide (stand-alone)

  Понеділок
  Вівторок
  Середа
  Четвер
  Пʼятниця
  Субота
  Неділя

=head3 Abbreviated (stand-alone)

  Пн
  Вт
  Ср
  Чт
  Пт
  Сб
  Нд

=head3 Narrow (stand-alone)

  П
  В
  С
  Ч
  П
  С
  Н

=head2 Months

=head3 Wide (format)

  січня
  лютого
  березня
  квітня
  травня
  червня
  липня
  серпня
  вересня
  жовтня
  листопада
  грудня

=head3 Abbreviated (format)

  січ.
  лют.
  бер.
  Кві
  Тра
  Чер
  Лип
  Сер
  Вер
  Жов
  Лис
  Гру

=head3 Narrow (format)

  С
  Л
  Б
  К
  Т
  Ч
  Л
  С
  В
  Ж
  Л
  Г

=head3 Wide (stand-alone)

  Січень
  Лютий
  Березень
  Квітень
  Травень
  Червень
  Липень
  Серпень
  Вересень
  Жовтень
  Листопад
  Грудень

=head3 Abbreviated (stand-alone)

  Січ.
  Лют.
  Бер.
  Кві
  Тра
  Чер
  Лип
  Сер
  Вер
  Жов
  Лис
  Гру

=head3 Narrow (stand-alone)

  С
  Л
  Б
  К
  Т
  Ч
  Л
  С
  В
  Ж
  Л
  Г

=head2 Quarters

=head3 Wide (format)

  I квартал
  II квартал
  III квартал
  IV квартал

=head3 Abbreviated (format)

  I кв.
  II кв.
  III кв.
  IV кв.

=head3 Narrow (format)

  I
  II
  III
  IV

=head3 Wide (stand-alone)

  I квартал
  II квартал
  III квартал
  IV квартал

=head3 Abbreviated (stand-alone)

  I кв.
  II кв.
  III кв.
  IV кв.

=head3 Narrow (stand-alone)

  1
  2
  3
  4

=head2 Eras

=head3 Wide

  до нашої ери
  нашої ери

=head3 Abbreviated

  до н.е.
  н.е.

=head3 Narrow

  до н.е.
  н.е.

=head2 Date Formats

=head3 Full

   2008-02-05T12:30:30 = Вівторок, 5 лютого 2008 р.
   1995-12-22T09:05:02 = Пʼятниця, 22 грудня 1995 р.
  -0010-12-22T23:05:02 = Субота, 22 грудня -010 р.

=head3 Long

   2008-02-05T12:30:30 = 5 лютого 2008 р.
   1995-12-22T09:05:02 = 22 грудня 1995 р.
  -0010-12-22T23:05:02 = 22 грудня -010 р.

=head3 Medium

   2008-02-05T12:30:30 = 5 лют. 2008
   1995-12-22T09:05:02 = 22 Гру 1995
  -0010-12-22T23:05:02 = 22 Гру -010

=head3 Short

   2008-02-05T12:30:30 = 05.02.8
   1995-12-22T09:05:02 = 22.12.95
  -0010-12-22T23:05:02 = 22.12.10

=head3 Default

   2008-02-05T12:30:30 = 5 лют. 2008
   1995-12-22T09:05:02 = 22 Гру 1995
  -0010-12-22T23:05:02 = 22 Гру -010

=head2 Time Formats

=head3 Full

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 12:30:30 UTC
   1995-12-22T09:05:02 = 09:05:02 UTC
  -0010-12-22T23:05:02 = 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 Default

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head2 Datetime Formats

=head3 Full

   2008-02-05T12:30:30 = Вівторок, 5 лютого 2008 р. 12:30:30 UTC
   1995-12-22T09:05:02 = Пʼятниця, 22 грудня 1995 р. 09:05:02 UTC
  -0010-12-22T23:05:02 = Субота, 22 грудня -010 р. 23:05:02 UTC

=head3 Long

   2008-02-05T12:30:30 = 5 лютого 2008 р. 12:30:30 UTC
   1995-12-22T09:05:02 = 22 грудня 1995 р. 09:05:02 UTC
  -0010-12-22T23:05:02 = 22 грудня -010 р. 23:05:02 UTC

=head3 Medium

   2008-02-05T12:30:30 = 5 лют. 2008 12:30:30
   1995-12-22T09:05:02 = 22 Гру 1995 09:05:02
  -0010-12-22T23:05:02 = 22 Гру -010 23:05:02

=head3 Short

   2008-02-05T12:30:30 = 05.02.8 12:30
   1995-12-22T09:05:02 = 22.12.95 09:05
  -0010-12-22T23:05:02 = 22.12.10 23:05

=head3 Default

   2008-02-05T12:30:30 = 5 лют. 2008 12:30:30
   1995-12-22T09:05:02 = 22 Гру 1995 09:05:02
  -0010-12-22T23:05:02 = 22 Гру -010 23:05:02

=head2 Available Formats

=head3 Ed (E d)

   2008-02-05T12:30:30 = Вт 5
   1995-12-22T09:05:02 = Пт 22
  -0010-12-22T23:05:02 = Сб 22

=head3 H (H)

   2008-02-05T12:30:30 = 12
   1995-12-22T09:05:02 = 9
  -0010-12-22T23:05:02 = 23

=head3 HHmm (HH:mm)

   2008-02-05T12:30:30 = 12:30
   1995-12-22T09:05:02 = 09:05
  -0010-12-22T23:05:02 = 23:05

=head3 HHmmss (HH:mm:ss)

   2008-02-05T12:30:30 = 12:30:30
   1995-12-22T09:05:02 = 09:05:02
  -0010-12-22T23:05:02 = 23:05:02

=head3 MMMEd (E MMM d)

   2008-02-05T12:30:30 = Вт лют. 5
   1995-12-22T09:05:02 = Пт Гру 22
  -0010-12-22T23:05:02 = Сб Гру 22

=head3 MMMMd (d MMMM)

   2008-02-05T12:30:30 = 5 лютого
   1995-12-22T09:05:02 = 22 грудня
  -0010-12-22T23:05:02 = 22 грудня

=head3 MMdd (dd.MM)

   2008-02-05T12:30:30 = 05.02
   1995-12-22T09:05:02 = 22.12
  -0010-12-22T23:05:02 = 22.12

=head3 Md (M-d)

   2008-02-05T12:30:30 = 2-5
   1995-12-22T09:05:02 = 12-22
  -0010-12-22T23:05:02 = 12-22

=head3 mmss (mm:ss)

   2008-02-05T12:30:30 = 30:30
   1995-12-22T09:05:02 = 05:02
  -0010-12-22T23:05:02 = 05:02

=head3 yyMM (MM.yy)

   2008-02-05T12:30:30 = 02.8
   1995-12-22T09:05:02 = 12.95
  -0010-12-22T23:05:02 = 12.10

=head3 yyMMM (LLL yy)

   2008-02-05T12:30:30 = Лют. 8
   1995-12-22T09:05:02 = Гру 95
  -0010-12-22T23:05:02 = Гру 10

=head3 yyQ (Q yy)

   2008-02-05T12:30:30 = 1 8
   1995-12-22T09:05:02 = 4 95
  -0010-12-22T23:05:02 = 4 10

=head3 yyyy (yyyy)

   2008-02-05T12:30:30 = 2008
   1995-12-22T09:05:02 = 1995
  -0010-12-22T23:05:02 = -010

=head3 yyyyMMMM (MMMM yyyy)

   2008-02-05T12:30:30 = лютого 2008
   1995-12-22T09:05:02 = грудня 1995
  -0010-12-22T23:05:02 = грудня -010

=head3 yyyyQQQQ (QQQQ yyyy 'р'.)

   2008-02-05T12:30:30 = I квартал 2008 р.
   1995-12-22T09:05:02 = IV квартал 1995 р.
  -0010-12-22T23:05:02 = IV квартал -010 р.

=head2 Miscellaneous

=head3 Prefers 24 hour time?

Yes

=head3 Local first day of the week

Понеділок


=head1 SUPPORT

See L<DateTime::Locale>.

=head1 AUTHOR

Dave Rolsky <autarch@urth.org>

=head1 COPYRIGHT

Copyright (c) 2008 David Rolsky. All rights reserved. This program is
free software; you can redistribute it and/or modify it under the same
terms as Perl itself.

This module was generated from data provided by the CLDR project, see
the LICENSE.cldr in this distribution for details on the CLDR data's
license.

=cut
